[package]
name = "methods_struct"
version = "0.1.0"
authors = ["Pierre <pi.laloy@laposte.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
